// console.log("java script is cool ")
// console.log = "java script is not a cool but he is coo;"
// console.log ="import js in sockets"
// console.log = "assembly is cool " + "jsscript is cool" + 4533 + "another string is cool "
// console.log = 43*43
// console.log = 43**5
// console.log = (`this is a multiple line /n/
// this is a second line of js/n/
// this is a third line of javascript/n/
// `)
// console.log='java is a cool'
// console.log("this is a single line script in this code")
// console.log(345)
// console.log(453)
// console.log(34545)
// console.log(43525)
// console.log("fsdggh")
// console.log(324)
// console.log(466666+45+354)
// console.log("sddg"+"sdsfsg")

// let myName ="sunil"
// let mySecondName = "kumar"
// let thirfName = "kumar"
// let conSiderd = "nameis"
// console.log(typeof mySecondName)
// console.log (typeof thirfName)
// console.log(myName)
// let mynameis = true
// let myNs = false
// let mysecondns = false
// let myage = 23.0
// console.log(typeof mynameis, typeof myNs,mysecondns,typeof myage)

// true;
// console.log(true)

// let myfirstName = 'sunil';
// mySecondName = "kuri";
// myAgeis = "20"
// mybirthdate = 2002;
// console.log(mySecondName)
// diffrent diffrent tyoes of valuses in he javascript this is a cool this is a cool code at me and my my name is sunil kumar kuro i am a learning programing so this is a cool thing at me and my or this is a cool thing i am a learning programing in the every time this is a cool habit of leaerning at coding with javascript this is a cool thing at me at our this is a cool thing a in the world and over the world is cover in this is a level
// let javascriptisFun = true;
// const javascriptnotFun = true;
// const age = 1934
// const agenow = 2023
// console.log(age-agenow);
// console.log(typeof age)
// console.log(typeof 1934);
// console.log(1934 > 2023)
// console.log(1934 >= 2023)
// console.log(age <= agenow)
// console.log(javascriptisFun);
// console.log(javascriptnotFun)

// methometical oprators in this code
// let age = 2023
// let myAge = 2002
// let sunita = 2004
// console.log(age- sunita)
// console.log(age - sunita > age - myAge)

// const firstName = "sunil";
// const mySecondName ="kuri";
// console.log(firstName + " " + mySecondName)

// //assingment oprators
// let x = 199+33
// x =+ 34
// x -= 45
// x *= 345
// console.log(x)
// const agenow = 2023;
// const agesocket = agenow - 2004;
// const agesunita = agenow - 2005;

// const avarage = agenow - 2054;
// console.log(agenow - agesocket);
// console.log(agenow - agesunita) / 2;
// console.log(agesocket, agesunita, avarage);

// c
// onst myfirstname = "suniil";
// const myworkis = " kriyayoaga";
// const myThird = " this is a my hacking";
// const Myage = 20;
// const mywokr = "hacking";
// const mySecondWork = "programing note just at work this is a string";
// const myFOurth = "thid id s ,y";
// console.log(
//   `my first name is ${myfirstname} my second name work ${mywokr},my third workd is a cool thing all the ${Myage}my second ${mySecondWork}`
// );
// if else and desion malking /////////////////////////
// const age = 5;
// const oldSocket = age >= 19;
// if (oldSocket) {
//   console.log(`this is a  taking $beacuse ${age}`);
// } else {
//   ("taking this coursr solidty");
// }
// const socketname = 2005;
// let socket2;
// if (socketname >= 2014) {
//   ("THIis is a take a time of coding ");
// } else {
//   ("take this is acourse worjing with you");
// }
// console.log(socket2);
